### ISSUE TITLE
Question about secondary development

### ISSUE THREAD

**Issue by Oddluo** [IRS-Cybersec/ctf_platform#163]
If I want to change some pictures, do you recommend me to change them through docker or bare metal?
Thanks ！！！

**Comment by Tkaixiang** [comment]
I would say docker is good enough! Simply change the images inside the ctf_platform/client folder (make sure they have the same name so they can be found) and rebuild the docker (`docker-compose up -d --build`) to update the docker with the new images

**Comment by Oddluo** [comment]
Thx！！！！Should I configure nginx if I want to access it through the intranet？

**Comment by Tkaixiang** [comment]
Yes you should, the docker container only exposes Port 20001 for the API and port 20002 for the client to `localhost`, so u need an nginx reverse proxy to make it available via intranet 

You can follow [here](https://github.com/IRS-Cybersec/ctf_platform/blob/master/ctf_platform.conf) and replace server_name with `_` so the platform is accessible via your servers intranet IP

**Comment by Oddluo** [comment]
hey, when i change the nginx.conf, the service can't start ,here my conf.
![图片](https://user-images.githubusercontent.com/67694128/146106469-78750443-49fa-451f-b4a1-1279c056abb7.png)
![图片](https://user-images.githubusercontent.com/67694128/146106521-ee3be105-9e5c-4928-a9c7-dd4172ff7e35.png)

**Comment by Tkaixiang** [comment]
Heyo, I should have mentioned that the ctf_platform.conf is simply a _part_ of an nginx.conf file (it's a server block). The full file looks like [this](https://www.nginx.com/resources/wiki/start/topics/examples/full/)

**Comment by Oddluo** [comment]
yep, I‘ve tried, here my conf , but it still can't work which makes me crazy
![图片](https://user-images.githubusercontent.com/67694128/146123857-7ff4d860-d571-448f-a1b9-2c130e689ea5.png)
![图片](https://user-images.githubusercontent.com/67694128/146123945-9bcb72c9-dc87-4e27-a780-ac3a83fc0c84.png)
![图片](https://user-images.githubusercontent.com/67694128/146124003-ce301035-fe71-4041-911c-ddc07c9c637d.png)

**Comment by Oddluo** [comment]
heyo, I've tried for this, but it didn't work..., here my conf 
![图片](https://user-images.githubusercontent.com/67694128/146125078-1d8869c5-25e9-4795-937e-226dbadc022e.png)
![图片](https://user-images.githubusercontent.com/67694128/146125050-6a4c9cca-fcdc-4d81-99be-73d9580afc39.png)
![图片](https://user-images.githubusercontent.com/67694128/146125111-52f2db5f-d69e-46c7-9836-6b5e0f131cbe.png)
![图片](https://user-images.githubusercontent.com/67694128/146125457-3ecea8c2-8fc7-453b-9d60-a47f58ee80aa.png)
![图片](https://user-images.githubusercontent.com/67694128/146125492-f1c4f5ec-60ac-4dc9-a08f-874ac4eb00ec.png)

**Comment by Tkaixiang** [comment]
Hi, can you send your full nginx.conf in a code block rather than screenshot?

**Comment by Oddluo** [comment]
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
	
	server {
        listen 80;
        listen [::]:80;
        server_name _;

        location /api/ {
                proxy_pass http://localhost:20001/;
                proxy_set_header    Host            $host;
                proxy_set_header    X-Real-IP       $remote_addr;
                proxy_set_header    X-Forwarded-for $remote_addr;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }

        location / {
                proxy_pass http://localhost:20002;
                proxy_set_header    Host            $host;
                proxy_set_header    X-Real-IP       $remote_addr;
                proxy_set_header    X-Forwarded-for $remote_addr;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }
}
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}

**Comment by Oddluo** [comment]
i'm sry, i don't know why did this happen, if you don't feel well, you can down the txt 

`user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
	
	server {
        listen 80;
        listen [::]:80;
        server_name _;

        location /api/ {
                proxy_pass http://localhost:20001/;
                proxy_set_header    Host            $host;
                proxy_set_header    X-Real-IP       $remote_addr;
                proxy_set_header    X-Forwarded-for $remote_addr;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }

        location / {
                proxy_pass http://localhost:20002;
                proxy_set_header    Host            $host;
                proxy_set_header    X-Real-IP       $remote_addr;
                proxy_set_header    X-Forwarded-for $remote_addr;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }
}
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}
`
[新建文本文档 (3).txt](https://github.com/IRS-Cybersec/ctf_platform/files/7716790/3.txt)

**Comment by Tkaixiang** [comment]
Hi, could you check your `include /etc/nginx/sites-enabled/*;` and `include /etc/nginx/conf.d/*.conf;` for any other server blocks? It seems like there might be another server block using `server_name _` (most likely the default nginx server block) as suggested by the error when you try to start nginx

**Comment by Oddluo** [comment]
Thx a lot !!!, i solved it by delete the file in include /etc/nginx/sites-enabled/default and now i can accesss it.

**Comment by Tkaixiang** [comment]
Np, I will be closing this now
