### ISSUE TITLE
关于得分榜功能开发

### ISSUE THREAD

**Issue by Oddluo** [IRS-Cybersec/ctf_platform#170]
作者您好，我对得分页面上有新的想法：

在同一页通过不同的category展示不同的category user 排行

目前只能选择单一category，展示单一排行，希望能增添至两个排行榜（数据展示自由度更高）。

Thx！！

**Comment by Tkaixiang** [comment]
您好，
这个在 d2734c39e134c414b1bc3c882190b12494da9796 已被加入。把 `/client/src/Scoreboard/Scoreboard.js` 换成 `/AlternativeClientFiles/Scoreboard/DoubleTable/Scoreboard.js` 就能用。
