### ISSUE TITLE
在使用docker安装时出现的问题

### ISSUE THREAD

**Issue by mcyydscc** [IRS-Cybersec/ctf_platform#237]
Step 4/10 : RUN npm ci --only=production
 ---> Running in c0a2aff4b53e
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
之后一直卡住不动

**Comment by Tkaixiang** [comment]
您好，请给我一天时间来修这个问题

**Comment by sheepymeh** [comment]
我也得到了同样的警告，可能是因为debian bullseye的node版本更新了。但是应该不会完全卡住，因为npm会连到网上自动修复package-lock.json。请确保你可以连接到npmjs.com，不行的话也可以试试看cnpm是否能用。

**Comment by Tkaixiang** [comment]
这个问题已在最新的版本修好了。请 `git pull` 再从新试试
