### ISSUE TITLE
`NODE_ENV` not set properly

### ISSUE THREAD

**Issue by 152334H** [IRS-Cybersec/ctf_platform#302]
This line:
https://github.com/IRS-Cybersec/ctf_platform/blob/78ca1b925f599770355ad9ce799859d905c37642/api/Dockerfile#L11

does absolutely nothing. You need to insert
```Dockerfile
ENV NODE_ENV production
```
to make it work.

I have no idea why your code works in spite of this

**Comment by Tkaixiang** [comment]
actually it probably works without this line because `pm2` by itself runs node modules in production. I will change it though for clarity sakes
