### ISSUE TITLE
Required challenge cannot be removed

### ISSUE THREAD

**Issue by 152334H** [IRS-Cybersec/ctf_platform#66]
steps to reproduce:

0. login to account with permissions >= 2 
1. create a challenge with a required challenge
2. try to remove that requirement

## bug source
In step 2, the frontend will fetch /v1/challenge/edit over here:

https://github.com/IRS-Cybersec/ctf_platform/blob/master/client/src/AdminPanel/adminChallengeEdit.js#L93-L111

When the value of an attribute is `undefined`, `JSON.stringify` will remove the attribute altogether.

https://github.com/IRS-Cybersec/ctf_platform/blob/master/api/api.js#L1022-L1025

The backend calls `updateOne()` with `$set`; because `updateObj` contains no `requires` attribute, the challenge requirement remains in the db

**Comment by Tkaixiang** [comment]
Fixed in 245d0f2fd5f1914fc2a7dc2a1e6303ca6e0923b5
